import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Idiomas | LANCELOT",
  description: "Entrenamiento de idiomas Lancelot: voz, comprensión, práctica deliberada y transferencia al mundo real."
};

const obstacles = [["Años de estudio", "Has estudiado durante años, pero aún no sientes que el idioma sea tuyo."], ["Conoces las reglas", "Sabes qué decir, pero la mente se bloquea cuando llega el momento de usarlo."], ["Olvido rápido", "La información entra, pero no encuentra una práctica que la convierta en dominio."], ["Miedo al pronunciar", "La inseguridad silencia una voz que sí puede construir pertenencia."]];
const method = [["01", "Escuchar", "Captación atencional profunda."], ["02", "Comprender", "Análisis estructural interno."], ["03", "Practicar", "Repetición y calibración."], ["04", "Feedback", "Ajuste guiado y preciso."], ["05", "Transferir", "Aplicación al mundo real."]];
const results = [["Confianza", "Seguridad al hablar en cualquier contexto."], ["Claridad", "Comunicación estructurada y precisa."], ["Comprensión profunda", "Entendimiento vivo de las estructuras."], ["Autonomía", "Capacidad de observarte, corregirte y avanzar."], ["Disciplina", "Hábitos de estudio que producen evidencia."], ["Memoria a largo plazo", "Retención duradera del conocimiento."], ["Transferencia real", "Aplicación a trabajo, reuniones, viajes o entrevistas."]];
const faqs = [["¿Es para nivel básico?", "Las dos rutas de Lancelot se adaptan desde un nivel básico hasta uno avanzado. No se trata de encajar en un nivel, sino de construir la autonomía del aprendiz para comprender, usar y hacer suyo el idioma. Esto es Lancelot."], ["¿Cuánto tiempo debo dedicar al día?", "Recomendamos entre 30 y 45 minutos diarios de práctica deliberada, complementados con las sesiones del programa elegido."], ["¿Cuál es la diferencia con un instituto tradicional?", "No se trata de acumular reglas ni de repetir ejercicios sin contexto. Entrenamos metacognición, precisión fonética y transferencia directa a tu realidad."]];

export default function IdiomasPage() {
  return <main className="languages-page">
    <nav className="languages-nav"><Link href="/" className="languages-brand" aria-label="Volver al inicio de Lancelot"><img src="/brand/lancelot-logo-official.png" alt="LANCELOT — Desde el ser para el saber" /></Link><div><a href="#programas">Programas</a><a href="#metodo">Metodología</a><Link className="languages-nav-cta" href="/#contacto">Conoce Lancelot</Link></div></nav>
    <section className="languages-hero" id="inicio"><div className="languages-shell languages-hero-grid"><div><p className="languages-kicker">Lancelot Idiomas · Centro de Entrenamiento del Aprendizaje</p><h1>Un idioma no se memoriza.<em>Se convierte en una forma de estar en el mundo.</em></h1><p className="languages-lead">Entrena tu voz, tu oído y tu pensamiento para comunicarte con precisión, confianza y presencia. En Lancelot, el idioma deja de ser una materia ajena y se vuelve una capacidad que puedes habitar.</p><div className="languages-actions"><Link className="languages-button languages-button-primary" href="#programas">Explorar programas <span>→</span></Link><Link className="languages-button languages-button-secondary" href="/#contacto">Conoce Lancelot <span>→</span></Link></div></div><aside className="languages-hero-visual"><img src="/brand/applications/idiomas.png" alt="Aprendiz en una experiencia de idiomas Lancelot" /><span>Voz · Criterio · Pertenencia</span></aside></div></section>

    <section className="languages-obstacles"><div className="languages-shell"><header className="languages-heading"><p className="languages-kicker">El problema no es tu capacidad</p><h2>Sabes más de lo que logras expresar.</h2><p>Cuando el aprendizaje se queda en reglas y contenido, el idioma no llega a convertirse en voz, presencia ni acción.</p></header><div>{obstacles.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="languages-programs" id="programas"><div className="languages-shell"><header className="languages-heading languages-heading-light"><p className="languages-kicker">Arquitectura del entrenamiento</p><h2>Dos rutas para que el idioma se vuelva tuyo.</h2></header><div className="languages-program-grid"><article><div className="languages-program-image"><img src="/brand/method-slider/sliderhome5.png" alt="Práctica de pronunciación y comunicación" /><span>Fase 01</span></div><div className="languages-program-copy"><p className="languages-program-label">Ruta Intensiva - 8 semanas</p><h3>Sound Sprint</h3><p>Entrena tu voz: dominio acústico, pronunciación americana y precisión articulatoria.</p><ul><li>3 sesiones por semana de 20 min</li><li>Foco en pronunciación americana</li><li>Práctica guiada y feedback preciso</li></ul><Link href="/#contacto">Conocer Sound Sprint <b>→</b></Link></div></article><article><div className="languages-program-image"><img src="/brand/method-slider/sliderhome2.png" alt="Aprendizaje profundo de estructuras de idioma" /><span>Fase 02</span></div><div className="languages-program-copy"><p className="languages-program-label">Ruta profunda · 16 semanas</p><h3>Grammar Journey</h3><p>Entrena tu comprensión: estructura profunda, metacognición y uso consciente del idioma.</p><ul><li>Modelo híbrido: sincrónico y asincrónico</li><li>Material exclusivo</li><li>Sesiones grupales de apoyo de 20 min</li></ul><Link href="/citas">Explorar esta ruta <b>→</b></Link></div></article></div></div></section>

    <section className="languages-method" id="metodo"><div className="languages-shell"><header className="languages-heading"><p className="languages-kicker">Metodología Lancelot</p><h2>Alto rendimiento, con el ser en el centro.</h2></header><div className="languages-method-grid">{method.map(([number, title, copy]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="languages-principles"><span>Metacognición activa</span><span>Doble Desbloqueo</span><span>Práctica deliberada</span></div></div></section>

    <section className="languages-results"><div className="languages-shell"><header className="languages-heading languages-heading-light"><p className="languages-kicker">Resultados</p><h2>Lo que lograrás va más allá de hablar.</h2></header><div>{results.map(([title, copy], index) => <article className={index === results.length - 1 ? "wide" : ""} key={title}><span>◇</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="languages-experience"><div className="languages-shell languages-experience-frame"><p className="languages-kicker">La experiencia</p><h2>Desde el Ser para el Saber</h2><p>Un viaje transformacional: no solo adquieres un idioma, transformas tu identidad como aprendiz. Construyes autonomía, resiliencia y una comprensión más profunda de tu mente frente al reto lingüístico.</p><div className="languages-audience"><span>Estudiantes</span><span>Profesionales</span><span>Viajeros</span><span>Amor por los idiomas</span></div><Link className="languages-button languages-button-primary" href="/#contacto">Comenzar mi entrenamiento <span>→</span></Link></div></section>

    <section className="languages-faq"><div className="languages-shell languages-faq-grid"><header><p className="languages-kicker">Información clara</p><h2>Preguntas frecuentes</h2></header><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="languages-closing"><div className="languages-shell"><p className="languages-kicker">Lancelot Idiomas</p><h2>El idioma no cambia únicamente la forma en que hablas.<em>Puede cambiar la forma en que ves el mundo.</em></h2><p>Descubre el poder de una comunicación precisa, estratégica y auténtica.</p><div className="languages-actions"><Link className="languages-button languages-button-gold" href="#programas">Arquitectura del entrenamiento <span>→</span></Link><Link className="languages-button languages-button-outline" href="/">Lancelot <span>→</span></Link></div></div></section>
    <footer className="languages-footer"><Link href="/"><img src="/brand/lancelot-logo-official.png" alt="LANCELOT" /></Link><span>© 2026 LANCELOT. Desde el ser para el saber.</span><nav><a href="#programas">Programas</a><a href="#metodo">Metodología</a><a href="#inicio">Idiomas</a></nav></footer>
  </main>;
}
