import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Orientación psicopedagógica | LANCELOT",
  description: "Orientación psicopedagógica y vocacional para comprender cómo aprendes y decidir tu próximo camino con claridad."
};

const challenges = [
  ["Hábitos ineficientes", "Estudiar horas sin retener información o repetir métodos que no funcionan para ti."],
  ["Ansiedad académica", "El estrés que paraliza antes de un examen o frente a un nuevo desafío intelectual."],
  ["Baja autorregulación", "Procrastinación constante y dificultad para sostener el enfoque en tareas complejas."],
  ["Bloqueos cognitivos", "La sensación de incapacidad frente a ciertas materias o tipos de información."],
  ["Falta de estrategias", "No contar con herramientas de aprendizaje que potencien tus habilidades naturales."],
  ["Decisiones sin autoconocimiento", "Elegir carreras o caminos profesionales por inercia, sin reconocer tus fortalezas."]
];

const services = [
  { title: "Orientación psicopedagógica", intro: "Descubre tu perfil de aprendizaje y desarrolla estrategias efectivas para superar bloqueos.", price: "$130.000 COP", booking: "/citas?encounterType=Diagnostico&service=Diagnostico%20de%20aprendizaje", details: ["Sesiones de 60 minutos.", "De 1 a 2 sesiones por semana.", "Se sugieren 12 sesiones para ver resultados de progreso.", "La primera sesión es de diagnóstico: busca comprender al aprendiz para diseñar y guiar su propio proceso."] },
  { title: "Orientación vocacional", intro: "Alinea tus capacidades con tus intereses para tomar decisiones profesionales informadas.", price: "$150.000 COP", booking: "/citas?encounterType=Consulta&service=Orientacion%20vocacional", details: ["Sesiones de 60 minutos.", "La cantidad de sesiones depende de la complejidad de la orientación.", "La primera sesión es de diagnóstico: busca comprender al aprendiz para diseñar y guiar su propio proceso.", "Un espacio para conectar tus intereses, capacidades y posibilidades de futuro."] }
];

const process = [["01", "Revela", "El aprendiz no llega vacío: llega con potencia que necesita forma, lenguaje y dirección."], ["02", "Organiza", "Cada ruta vuelve visible el proceso mental para que la persona entienda cómo aprende."], ["03", "Ejercita", "La disciplina se convierte en práctica deliberada, evidencia y progreso visible."], ["04", "Transfiere", "El conocimiento se prueba cuando cambia decisiones, voz, criterio o acción."]];
const audiences = ["Estudiantes escolares", "Universitarios", "Profesionales", "Padres de familia", "Aprendices de idiomas", "Buscadores de reinvención", "Desertores de cursos", "Buscadores vocacionales"];
const faqs = [["¿Cuál es la diferencia entre tutoría y orientación psicopedagógica?", "La tutoría se enfoca en el contenido: enseñar matemáticas, historia u otra materia. La orientación psicopedagógica se enfoca en el proceso: comprender cómo aprendes para que puedas abordar cualquier materia con más claridad."], ["¿Cuánto dura un proceso típico?", "Un proceso estándar se estima en 12 sesiones para ver resultados de progreso. Recomendamos una frecuencia mínima de una sesión semanal y un máximo de dos para garantizar un avance constante."], ["¿Hacen pruebas psicológicas o diagnósticos médicos?", "Realizamos una sesión inicial de diagnóstico profundo para conocer al aprendiz, identificar bloqueos específicos y trazar un mapa personalizado de potencial. No sustituye diagnósticos médicos o psicológicos."], ["¿A partir de qué edad recomiendan sus servicios?", "No hay límite de edad. Los programas se adaptan a las necesidades específicas de cada aprendiz y a su momento de vida."], ["¿Las sesiones son presenciales o virtuales?", "Las sesiones son 100 % virtuales. La metodología está diseñada para acompañar desde un espacio seguro, eliminar barreras geográficas y facilitar el seguimiento del progreso."]];

export default function OrientacionPage() {
  return <main className="orientation-page">
    <nav className="orientation-nav" aria-label="Navegación de orientación"><Link className="orientation-brand" href="/" aria-label="Volver al inicio de Lancelot"><img src="/brand/lancelot-logo-official.png" alt="LANCELOT — Desde el ser para el saber" /></Link><div className="orientation-nav-links"><a href="#servicios">Servicios</a><a href="#metodo">Método</a><Link className="orientation-nav-cta" href="/citas?encounterType=Diagnostico&service=Diagnostico%20de%20aprendizaje">Agendar orientación</Link></div></nav>

    <section className="orientation-hero" id="inicio"><div className="orientation-shell orientation-hero-grid"><div className="orientation-hero-copy"><p className="orientation-kicker">Orientación psicopedagógica y vocacional</p><h1>Tal vez el problema nunca fue aprender.</h1><p className="orientation-hero-statement">Solo nadie te enseñó cómo aprendes.</p><p className="orientation-lead">Comprende tu forma de aprender, reconoce los bloqueos que limitan tu desarrollo y encuentra un camino académico y profesional con mayor claridad.</p><div className="orientation-actions"><Link className="orientation-button orientation-button-primary" href="/citas?encounterType=Diagnostico&service=Diagnostico%20de%20aprendizaje">Iniciar mi proceso <span aria-hidden="true">→</span></Link><a className="orientation-button orientation-button-secondary" href="#metodo">Conocer el método <span aria-hidden="true">↓</span></a></div></div><aside className="orientation-hero-panel" aria-label="Promesa de orientación Lancelot"><span className="orientation-panel-number">01</span><img src="/brand/applications/aprendices.png" alt="Aprendiz acompañado por Lancelot" /><div><p>Desde el ser para el saber</p><strong>Claridad para comprender, decidir y avanzar.</strong></div></aside></div></section>

    <section className="orientation-challenges"><div className="orientation-shell"><header className="orientation-section-heading"><p className="orientation-kicker">El punto de partida</p><h2>¿Por qué aprender puede sentirse tan difícil?</h2><p>No se trata de una falta de capacidad. A veces hace falta ver el proceso con otro lenguaje, una estrategia más propia y una dirección que tenga sentido.</p></header><div className="orientation-challenge-grid">{challenges.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><blockquote>“Comprender cómo aprendes es el primer paso para transformar cualquier aprendizaje y tomar mejores decisiones sobre tu futuro.”</blockquote></div></section>

    <section className="orientation-services" id="servicios"><div className="orientation-shell"><header className="orientation-section-heading orientation-heading-light"><p className="orientation-kicker">Acompañamiento individual</p><h2>Dos caminos para avanzar con dirección.</h2></header><div className="orientation-service-grid">{services.map((service, index) => <article className="orientation-service-card" key={service.title}><p className="orientation-card-index">0{index + 1}</p><h3>{service.title}</h3><p className="orientation-service-intro">{service.intro}</p><ul>{service.details.map((detail) => <li key={detail}>{detail}</li>)}</ul><div className="orientation-price"><span>Valor por sesión</span><strong>{service.price}</strong></div><Link className="orientation-card-link" href={service.booking}>Agendar primera sesión <span aria-hidden="true">→</span></Link></article>)}</div></div></section>

    <section className="orientation-method" id="metodo"><div className="orientation-shell"><header className="orientation-section-heading orientation-heading-light"><p className="orientation-kicker">Metodología Lancelot</p><h2>Del bloqueo a una relación más consciente con aprender.</h2><p>El acompañamiento no termina en una técnica. Busca transformar la manera en la que una persona se observa, se organiza, practica y lleva lo aprendido a su vida.</p></header><div className="orientation-process">{process.map(([number, title, copy]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="orientation-double"><div className="orientation-shell orientation-double-grid"><div className="orientation-double-visual" aria-hidden="true"><div><span>Capacidad</span><p>Lo que puedes hacer.</p></div><div><span>Facultad</span><p>En quién puedes convertirte.</p></div></div><div><p className="orientation-kicker">Principio Lancelot</p><h2>El Doble Desbloqueo</h2><p className="orientation-double-lead">Toda filosofía necesita una columna vertebral. Para LANCELOT, esa idea es la unión entre lo que puedes hacer y en quién te conviertes.</p><div className="orientation-double-notes"><article><h3>Desbloqueo de capacidad</h3><p>Mejora tangible en rendimiento, comprensión, retención y aplicación de conocimientos.</p></article><article><h3>Desbloqueo de facultad</h3><p>Evolución en autoconcepto, confianza, resiliencia ante desafíos intelectuales y autonomía.</p></article></div><p className="orientation-quote">“Ninguna clase termina en el contenido. Termina en la persona que el contenido ayudó a revelar.”</p></div></div></section>

    <section className="orientation-audiences"><div className="orientation-shell"><header className="orientation-section-heading"><p className="orientation-kicker">Una orientación que se adapta</p><h2>¿Para quién es?</h2></header><div>{audiences.map((audience, index) => <span key={audience}><b>{String(index + 1).padStart(2, "0")}</b>{audience}</span>)}</div></div></section>
    <section className="orientation-faq"><div className="orientation-shell orientation-faq-grid"><div><p className="orientation-kicker">Información clara</p><h2>Preguntas frecuentes</h2><p>La primera sesión crea un punto de partida. Desde allí se define el proceso que corresponde a cada aprendiz.</p></div><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="orientation-closing"><div className="orientation-shell orientation-closing-frame"><img src="/brand/lancelot-logo-official.png" alt="LANCELOT" /><p className="orientation-kicker">Un siguiente paso con sentido</p><h2>Comprender cómo aprendes puede cambiar la forma en que construyes tu futuro.</h2><p>La orientación educativa no es solo para quienes tienen dificultades; es para cualquiera que desea optimizar su capacidad natural. En LANCELOT, transformamos la frustración en claridad metodológica.</p><Link className="orientation-button orientation-button-gold" href="/citas?encounterType=Diagnostico&service=Diagnostico%20de%20aprendizaje">Agendar orientación <span aria-hidden="true">→</span></Link></div></section>
    <footer className="orientation-footer"><Link href="/"><img src="/brand/lancelot-logo-official.png" alt="LANCELOT" /></Link><p>© 2026 LANCELOT. Desde el ser para el saber.</p><nav><a href="#servicios">Servicios</a><a href="#metodo">Método</a><Link href="/">Inicio</Link></nav></footer>
  </main>;
}
